# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: tf-code-analyzer-agntcy-agent
namespace: prcoach-dev
appVersion: v1
replicaCount: 1

image:
  repository: ghcr.io/cisco-outshift-ai-agents/tf-code-analyzer-agntcy-agent:latest
  tag: latest
  pullPolicy: Always
  pullSecret:

service:
  port: 8133

# serviceaccount:
#   annotations:
#     eks.amazonaws.com/role-arn: REPLACE_WITH_ROLE_ARN

probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  port: 8133
  endpoint: /v1/health


azureOpenAi:
  endpoint: ""
  deploymentName: ""
  apiVersion: ""

openAi:
  temperature: "0.7"

resources:
  enabled: false
  limits:
    cpu: 2000m
    memory: 2500Mi
  requests:
    cpu: 200m
    memory: 500Mi
