name: "Terraform Analyzer CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TF_CODE_ANALYZER_HOST: "127.0.0.1"
      TF_CODE_ANALYZER_PORT: "8133"
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_REPO_URL: ${{ secrets.GITHUB_REPO_URL }}
      GITHUB_BRANCH: ${{ secrets.GITHUB_BRANCH }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libyaml-dev
        python -m pip install --upgrade pip wheel setuptools

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --only-binary :all: PyYAML
        pip install pytest pytest-asyncio pytest-cov pytest-mock
        make install

    - name: Build and start services
      run: |
        make docker-up
        sleep 10  # Wait for services to be ready
        docker ps

    - name: Run All Tests
      run: |
        # Ensure pytest is in PATH
        export PATH=$PATH:$(python -m site --user-base)/bin
        make test

    - name: Cleanup
      if: always()
      run: make docker-down