name: Terraform Analyzer Agent CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AGP_GATEWAY_ENDPOINT: ${{ secrets.AGP_GATEWAY_ENDPOINT }}
  AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
  AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_REPO_URL: ${{ secrets.GITHUB_REPO_URL }}
  GITHUB_BRANCH: ${{ secrets.GITHUB_BRANCH }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio docker-compose

    - name: Build and start services
      run: |
        docker-compose up -d --build agp-gateway tf-code-analyzer
        sleep 10  # Wait for services to be ready
        docker ps

    
    - name: Cleanup
      if: always()
      run: docker-compose down 