name: "Terraform Analyzer CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TF_CODE_ANALYZER_HOST: "127.0.0.1"
      TF_CODE_ANALYZER_PORT: "8133"
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_REPO_URL: ${{ secrets.GITHUB_REPO_URL }}
      GITHUB_BRANCH: ${{ secrets.GITHUB_BRANCH }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Approach 1: Install build dependencies first
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libyaml-dev
        python -m pip install --upgrade pip wheel setuptools

    # Approach 2: Use pre-built wheels
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --only-binary :all: PyYAML  # Force using pre-built wheel
        make install

    - name: Build and start services
      run: |
        make docker-up
        sleep 10  # Wait for services to be ready
        docker ps

    - name: Run All Tests
      run: make test

    - name: Cleanup
      if: always()
      run: make docker-down